version: '3.8'

services:
  pentaho_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./pentaho-server:/home/ubuntu/pentaho/pentaho-server
      - pentaho_data:/home/ubuntu/pentaho/data
    environment:
      JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    command: ["sh", "-c", "./start-pentaho.sh && tail -f /dev/null"]


volumes:
  pentaho_data: